use anyhow::Result;
use serde::{Deserialize, Serialize};
use std::path::Path;

/// The structure of `Beru.lock`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BeruLock {
    /// The format version of the lockfile (e.g. 1)
    pub version: u32,
    /// The resolved and locked dependencies
    #[serde(default, rename = "package")]
    pub packages: Vec<LockedPackage>,
}

/// A fully resolved dependency in the lockfile.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LockedPackage {
    /// The name of the package.
    pub name: String,
    /// The exact resolved version.
    pub version: String,
    /// The source URL or path where it was fetched from.
    pub source: String,
    /// The git revision or sha256 hash.
    #[serde(default)]
    pub checksum: Option<String>,
    /// Dependencies this package relies on.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub dependencies: Vec<String>,
}

impl BeruLock {
    /// Parse a `Beru.lock` from a string.
    pub fn from_str(content: &str) -> Result<Self, toml::de::Error> {
        toml::from_str(content)
    }

    /// Read `Beru.lock` from a directory.
    pub fn from_dir(dir: &Path) -> anyhow::Result<Self> {
        let lock_path = dir.join("Beru.lock");
        let content = std::fs::read_to_string(&lock_path)?;
        Ok(Self::from_str(&content)?)
    }

    /// Serialize the lockfile to a string.
    pub fn to_string(&self) -> Result<String, toml::ser::Error> {
        let mut out = String::from(
            "# This file is automatically generated by Beru.\n# It is not intended for manual editing.\n",
        );
        out.push_str(&toml::to_string(self)?);
        Ok(out)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_lockfile() {
        let toml = r#"
version = 1

[[package]]
name = "fmt"
version = "11.0.2"
source = "https://github.com/fmtlib/fmt"
checksum = "6cb1e6d37bdcb756dbbe59be438790db409cdb4868c66e888d5df9f13f7c027f"

[[package]]
name = "spdlog"
version = "1.14.1"
source = "https://github.com/gabime/spdlog"
dependencies = ["fmt"]
"#;
        let lock = BeruLock::from_str(toml).unwrap();
        assert_eq!(lock.version, 1);
        assert_eq!(lock.packages.len(), 2);
        assert_eq!(lock.packages[0].name, "fmt");
        assert_eq!(lock.packages[1].dependencies.len(), 1);
        assert_eq!(lock.packages[1].dependencies[0], "fmt");
    }
}
