[package]
name = "opencv"
version = "4.10.0"
type = "library"
description = "Open Source Computer Vision Library"

[source]
url = "https://github.com/opencv/opencv/archive/refs/tags/4.10.0.tar.gz"
sha256 = "b2171af5be6b26f7a06b1229948b9bfcbdb1bc58ce904b7adf6eeaa394fcf43e"

[build]
system = "cmake"
cmake-args = [
    "-DBUILD_TESTS=OFF",
    "-DBUILD_PERF_TESTS=OFF",
    "-DBUILD_EXAMPLES=OFF",
    "-DWITH_CUDA=OFF",
    "-DBUILD_LIST=core,imgproc"
]

[export]
include-dirs = ["include/opencv4"]
link-libs = ["opencv_core", "opencv_imgproc"]
cmake-package = "OpenCV"
cmake-targets = ["opencv_core", "opencv_imgproc"]
