use anyhow::{Context, Result};
use std::path::Path;
use tracing::info;

/// Metadata about a dependency for CMake linking.
pub struct CMakeDependency {
    /// The CMake package name to find (e.g. `fmt`).
    pub package_name: Option<String>,
    /// The CMake targets to link (e.g. `fmt::fmt`).
    pub targets: Vec<String>,
}

/// Generate a `beru-toolchain.cmake` file that wires Beru-managed
/// dependencies into a user's CMake project.
///
/// The toolchain file:
/// - Prepends each dependency's install prefix to `CMAKE_PREFIX_PATH`
/// - Sets `CMAKE_CXX_STANDARD` from the manifest's `cxx-std`
/// - Sets build type and optimization flags from the profile
/// - Defines `beru_link_dependencies()` to auto-link `cmake_deps`
///
/// Users invoke their CMake build with:
/// ```sh
/// cmake -B build -DCMAKE_TOOLCHAIN_FILE=beru-toolchain.cmake
/// ```
pub fn generate_toolchain_cmake(
    output_path: &Path,
    cxx_std: &str,
    build_type: &str,
    prefix_paths: &[&Path],
    cmake_deps: &[CMakeDependency],
) -> Result<()> {
    let cxx_standard_number = cxx_std_to_number(cxx_std);

    let mut content = String::new();

    content.push_str("# Generated by Beru — do not edit manually\n");
    content.push_str("# This file is regenerated on every `beru build`\n\n");

    content.push_str(&format!(
        "set(CMAKE_CXX_STANDARD {} CACHE STRING \"C++ standard (set by Beru)\")\n",
        cxx_standard_number
    ));
    content.push_str("set(CMAKE_CXX_STANDARD_REQUIRED ON CACHE BOOL \"\")\n");
    content.push_str("set(CMAKE_CXX_EXTENSIONS OFF CACHE BOOL \"\")\n\n");

    let cmake_build_type = match build_type {
        "debug" => "Debug",
        "release" => "Release",
        "relwithdebinfo" => "RelWithDebInfo",
        "minsizerel" => "MinSizeRel",
        other => other,
    };
    content.push_str(&format!(
        "set(CMAKE_BUILD_TYPE {} CACHE STRING \"Build type (set by Beru)\")\n\n",
        cmake_build_type
    ));

    if !prefix_paths.is_empty() {
        content.push_str("# Beru-managed dependency install prefixes\n");
        content.push_str("set(CMAKE_PREFIX_PATH\n");
        for path in prefix_paths {
            let escaped = path.to_string_lossy().replace('\\', "/");
            content.push_str(&format!("    \"{}\"\n", escaped));
        }
        content.push_str("    ${CMAKE_PREFIX_PATH}\n");
        content.push_str("    CACHE STRING \"Beru prefixes\" FORCE\n");
        content.push_str(")\n\n");
    }

    content.push_str("# Set RPATH for installed binaries\n");
    content.push_str("set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE CACHE BOOL \"\")\n\n");

    content.push_str("# ---------------------------------------------------------\n");
    content.push_str("# Beru Magic Macro: Automatically link all dependencies\n");
    content.push_str("# ---------------------------------------------------------\n");
    content.push_str("macro(beru_link_dependencies TARGET_NAME)\n");

    for path in prefix_paths {
        let escaped = path.to_string_lossy().replace('\\', "/");
        content.push_str(&format!(
            "    target_include_directories(${{TARGET_NAME}} PRIVATE \"{}/include\")\n",
            escaped
        ));
        content.push_str(&format!(
            "    target_link_directories(${{TARGET_NAME}} PRIVATE \"{}/lib\")\n",
            escaped
        ));
    }

    let mut sorted_deps = cmake_deps.iter().collect::<Vec<_>>();
    sorted_deps.sort_by_key(|d| d.package_name.as_deref().unwrap_or(""));

    for dep in sorted_deps {
        if let Some(pkg) = &dep.package_name {
            content.push_str(&format!("    find_package({} QUIET)\n", pkg));
        }
        for target in &dep.targets {
            content.push_str(&format!(
                "    target_link_libraries(${{TARGET_NAME}} PRIVATE {})\n",
                target
            ));
        }
    }
    content.push_str("endmacro()\n\n");

    std::fs::write(output_path, &content)
        .with_context(|| format!("failed to write {}", output_path.display()))?;

    info!("generated {}", output_path.display());

    Ok(())
}

/// Convert a `cxx-std` string (e.g. `"c++20"`) to a CMake standard number (e.g. `"20"`).
fn cxx_std_to_number(cxx_std: &str) -> &str {
    match cxx_std {
        "c++11" => "11",
        "c++14" => "14",
        "c++17" => "17",
        "c++20" => "20",
        "c++23" => "23",
        "c++26" => "26",
        _ => "17",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn test_cxx_std_to_number() {
        assert_eq!(cxx_std_to_number("c++20"), "20");
        assert_eq!(cxx_std_to_number("c++17"), "17");
        assert_eq!(cxx_std_to_number("c++11"), "11");
    }

    #[test]
    fn test_generate_toolchain() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("beru-toolchain.cmake");
        let prefix = PathBuf::from("/home/user/.beru/cache/builds/abc123/fmt-11.0.2");

        generate_toolchain_cmake(&path, "c++20", "release", &[prefix.as_path()], &[]).unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("CMAKE_CXX_STANDARD 20"));
        assert!(content.contains("Release"));
        assert!(content.contains("fmt-11.0.2"));
    }
}
