# Generated by Beru — do not edit manually
# This file is regenerated on every `beru build`

set(CMAKE_CXX_STANDARD 20 CACHE STRING "C++ standard (set by Beru)")
set(CMAKE_CXX_STANDARD_REQUIRED ON CACHE BOOL "")
set(CMAKE_CXX_EXTENSIONS OFF CACHE BOOL "")

set(CMAKE_BUILD_TYPE Debug CACHE STRING "Build type (set by Beru)")

# Beru-managed dependency install prefixes
list(PREPEND CMAKE_PREFIX_PATH
    "/home/adityaanand/.beru/cache/builds/b8a7e2179ced9fe2c0407138650f35b7/catch2-3.7.1"
)

# Set RPATH for installed binaries
set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE CACHE BOOL "")
